### ISSUE TITLE
Lines column color

### ISSUE THREAD

**Issue by aretekzs** [novasenco/nokto#1]
Is it possible to change the lines column number? I've tried changing the values in the nokto.vim file but to no success.

**Comment by novasenco** [comment]
Probably. What do you want to change?

It seems like you want to change here: https://github.com/novasenco/nokto/blob/main/colors/nokto.vim#L191

You can add this into your vimrc, too.

```vim
augroup myAugroup
    autocmd!
    autocmd ColorScheme nokto highlight LineNr ctermfg=red guifg=red
augroup end
```

for example.

If you want to change the current line's LineNr, then you need to modify `CursorLineNr`.

---

I don't use line numbers much, so I am open to suggestions about what color they should be.

**Comment by aretekzs** [comment]
I want to change the column on the left to match the black background: 

![github](https://user-images.githubusercontent.com/63618062/101881130-e09fe400-3b8b-11eb-92c2-b09a1b242174.png)

I've tried changing L191 and adding that to my .vimrc but to no success, the color won't change.

**Comment by novasenco** [comment]
I understand now. Before you call `colorscheme nokto` in your vimrc, if you add this:

```vim
augroup sldx_vimrc
    autocmd!
    autocmd ColorScheme nokto highlight LineNr ctermbg=NONE guibg=NONE
augroup end
```

then ... it will fix it.

---

Also, see attached screenshot for clarity:

![foo](https://user-images.githubusercontent.com/62544937/114441544-85ade600-9b99-11eb-934c-4d087fc7df22.png)

**Comment by novasenco** [comment]
Although I could make this the default background, I don't want to. The reason is because I have designed each of the colors to be very low contrast with each other (even though they are high contrast to the background). This is because I feel high contrast between different syntax elements can be very distracting. Since the line numbers are also very low contrast with respect to the purple, I added a light grey background to make them noticeably not part of the buffer.

I could, however, make the line numbers higher contrast with a transparent background. This would mean that it would be viable to have a transparent background for the numbes but you would still easily be able to distinguish them from the buffer text.

What do you think?

Also, if my replies resolved your answer, you can close the issue if you want.

**Comment by novasenco** [comment]
I wanted `Visual` to keep the foreground color. Since I was making a change, I updated `lineNr*` to have no background. I think it looks fine enough, and I don't use 'nu' anyway. So, I am closing the issue now.
